#!/bin/sh

LAPTOP="eDP"
LEFT="DisplayPort-2"
RIGHT="DisplayPort-1"
DOCKED_DPI="96"
LAPTOP_DPI="110"

is_connected() {
    xrandr --query | grep -q "^$1 connected"
}

workspace_exists() {
    i3-msg -t get_workspaces | grep -q "\"name\":\"$1\""
}

move_ws_if_exists() {
    ws="$1"
    output="$2"

    if workspace_exists "$ws"; then
        i3-msg "[workspace=\"$ws\"] move workspace to output $output" >/dev/null
    fi
}

WS_TERM="1:term"
WS_FIREFOX="2:web"
WS_CODE="3:code"
WS_EMAIL="4:mail"
WS_FILES="5:files"
WS_DOCS="6:pdfs"
WS_SPOTIFY="7:music"
WS_MISC="8:misc"
WS_VM="9:vm"
WS_EXTRA="10:extra"

if is_connected "$LEFT" && is_connected "$RIGHT"; then
    xrandr --dpi "$DOCKED_DPI"

    move_ws_if_exists "$WS_FIREFOX" "$LEFT"
    move_ws_if_exists "$WS_CODE" "$RIGHT"
    move_ws_if_exists "$WS_TERM" "$LAPTOP"
    move_ws_if_exists "$WS_SPOTIFY" "$LAPTOP"

    move_ws_if_exists "$WS_EMAIL" "$LAPTOP"
    move_ws_if_exists "$WS_DOCS" "$RIGHT"
    move_ws_if_exists "$WS_FILES" "$RIGHT"
    move_ws_if_exists "$WS_MISC" "$LAPTOP"
    move_ws_if_exists "$WS_VM" "$RIGHT"
    move_ws_if_exists "$WS_EXTRA" "$RIGHT"
else
    xrandr --dpi "$LAPTOP_DPI"

    for ws in \
        "$WS_TERM" "$WS_FIREFOX" "$WS_CODE" "$WS_EMAIL" "$WS_FILES" \
        "$WS_DOCS" "$WS_SPOTIFY" "$WS_MISC" "$WS_VM" "$WS_EXTRA"
    do
        move_ws_if_exists "$ws" "$LAPTOP"
    done
fi
